//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Msg
    {
        public int MsgID { get; set; }
        public string MsgTitle { get; set; }
        public string MsgText { get; set; }
        public string MsgType { get; set; }
        public string MsgPhoto { get; set; }
        public System.DateTime MsgTime { get; set; }
        public Nullable<int> MsgHit { get; set; }
        public Nullable<int> AccountID { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
